### ISSUE TITLE
Problem with set_bmc_credentials

### ISSUE THREAD

**Issue by Matze1992** [RackHD/on-taskgraph#179]
Hi at all,

i have Problem with the Task.Set.BMC.Credentials. Please see the error below.

`
6:48:39 PM graph.1  |  graphName: Graph.Set.Bmc.Credentials

6:48:39 PM graph.1  |  error:

6:48:39 PM graph.1  |    stack:

6:48:39 PM graph.1  |      - Error: Task.Set.BMC.Credentials: JSON schema validation failed - data.password should NOT be longer than 20 characters, data.password should match pattern "^[ -~]{1,20}$"

6:48:39 PM graph.1  |      -     at TaskOptionValidator.JsonSchemaValidator.validatePatternsSkipped (/root/src/on-taskgraph/node_modules/on-core/lib/common/json-schema-validator.js:94:23)

6:48:39 PM graph.1  |      -     at TaskOptionValidator.validateContextSkipped (/root/src/on-taskgraph/node_modules/on-tasks/lib/utils/task-option-validator.js:61:21)

6:48:39 PM graph.1  |      -     at /root/src/on-taskgraph/node_modules/on-tasks/lib/task.js:450:31

6:48:39 PM graph.1  |      -     at tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)

6:48:39 PM graph.1  |      -     at Promise._settlePromiseFromHandler (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)

6:48:39 PM graph.1  |      -     at Promise._settlePromiseAt (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)

6:48:39 PM graph.1  |      -     at Promise._settlePromises (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)

6:48:39 PM graph.1  |      -     at Async._drainQueue (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)

6:48:39 PM graph.1  |      -     at Async._drainQueues (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)

6:48:39 PM graph.1  |      -     at Immediate.Async.drainQueues [as _onImmediate] (/root/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)

6:48:39 PM graph.1  |      -     at processImmediate [as _immediateCallback] (timers.js:383:17)

6:48:39 PM graph.1  |    message:       Task.Set.BMC.Credentials: JSON schema validation failed - data.password should NOT be longer than 20 characters, data.password should match pattern "^[ -~]{1,20}$"

6:48:39 PM graph.1  |    errorList:

6:48:39 PM graph.1  |      -

6:48:39 PM graph.1  |        keyword:      maxLength

6:48:39 PM graph.1  |        dataPath:     .password

6:48:39 PM graph.1  |        schemaPath:   #/definitions/Password/maxLength

6:48:39 PM graph.1  |        params:

6:48:39 PM graph.1  |          limit: 20

6:48:39 PM graph.1  |        message:      should NOT be longer than 20 characters

6:48:39 PM graph.1  |        schema:       20

6:48:39 PM graph.1  |        parentSchema:

6:48:39 PM graph.1  |          description: The IPMI password

6:48:39 PM graph.1  |          type:        string

6:48:39 PM graph.1  |          minLength:   1

6:48:39 PM graph.1  |          maxLength:   20

6:48:39 PM graph.1  |          pattern:     ^[ -~]{1,20}$

6:48:39 PM graph.1  |        data:         p/MNxuYafRAgBE6kga/5KA==.GEdmdIASshvios0mvP05gA==

6:48:39 PM graph.1  |      -

6:48:39 PM graph.1  |        keyword:      pattern

6:48:39 PM graph.1  |        dataPath:     .password

6:48:39 PM graph.1  |        schemaPath:   #/definitions/Password/pattern

6:48:39 PM graph.1  |        params:

6:48:39 PM graph.1  |          pattern: ^[ -~]{1,20}$

6:48:39 PM graph.1  |        message:      should match pattern "^[ -~]{1,20}$"

6:48:39 PM graph.1  |        schema:       ^[ -~]{1,20}$

6:48:39 PM graph.1  |        parentSchema:

6:48:39 PM graph.1  |          description: The IPMI password

6:48:39 PM graph.1  |          type:        string

6:48:39 PM graph.1  |          minLength:   1

6:48:39 PM graph.1  |          maxLength:   20

6:48:39 PM graph.1  |          pattern:     ^[ -~]{1,20}$

6:48:39 PM graph.1  |        data:         p/MNxuYafRAgBE6kga/5KA==.GEdmdIASshvios0mvP05gA==

6:48:39 PM graph.1  |    isOperational: true

6:48:39 PM graph.1  |  [error] [2016-10-25T16:48:39.197Z] [on-taskgraph] [Task.Task] [Server] Task failed

6:48:39 PM graph.1  |   -> /node_modules/on-tasks/lib/task.js:353

6:48:39 PM graph.1  |  error:          Error: Task.Set.BMC.Credentials: JSON schema validation failed - 
data.password should NOT be longer than 20 characters, data.password should match pattern "^[ -~]{1,20}$"
`

I have absolutly no idea, why the generate-bmc-password.js job generate a to long password.
Can someone help please?

**Comment by leoyjchang** [comment]
@Matze1992, can you please provide the API call and full input payload you are using to invoke taskgraph "Graph.Set.Bmc.Credentials"?  + @yyscamper

**Comment by Matze1992** [comment]
Hi leoyjchang,

okay, the workflow ist the SKU Discovery Graph. I have make the changes in the graphs wich are documented here: http://rackhd.readthedocs.io/en/latest/rackhd/configuration.html?highlight=bmc

You can see the API of the two graphs below.
[discovery-graph.txt](https://github.com/RackHD/on-taskgraph/files/552547/discovery-graph.txt)
[discovery-sku-graph.txt](https://github.com/RackHD/on-taskgraph/files/552546/discovery-sku-graph.txt)

And here the GUI Overview:
[Graphs.pdf](https://github.com/RackHD/on-taskgraph/files/552554/Graphs.pdf)

I hope that these information are helpfully for you. 
Thanks!

**Comment by yyscamper** [comment]
@Matze1992 : After some debugging, I believe this PR (https://github.com/RackHD/on-tasks/pull/363) will fix your problem.

The root cause is: the password is encrypted before storing to database, but it never be decrypted when the task wants to use its original value.

**Comment by leoyjchang** [comment]
Thanks @yyscamper . @Matze1992 could you verify Felix's finding? I will close this issue if it gets resolved.
